steps:
# Step 1: Build the Docker image
- id: 'build-container'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '$_FULL_BUILD_NAME:$_TAG_PREFIX$SHORT_SHA'
  - '.'
  waitFor: ['-']

- id: 'update-image-tag'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
      ls -l
      echo "Starting update-image-tag step"
      echo "BRANCH_NAME: $BRANCH_NAME, SHORT_SHA: $SHORT_SHA"
      
      git config user.email "696197326044@cloudbuild.gserviceaccount.com"
      git config user.name "GCP Cloudbuild"
      
      echo "Git user set"
    
      echo "git clone $_GIT_REPOSITORY repo"
      git clone $_GIT_REPOSITORY repo
      cd repo
      
      echo "git checkout $BRANCH_NAME"
      git checkout $BRANCH_NAME
    
      sed -i 's|tag:.*|tag: "'$SHORT_SHA'"|' ./helm/values.yaml
    
      echo "git diff"
      git diff
      
      echo "git diff --quiet && git diff --staged --quiet || (git add helm/values.yaml && git commit -m "Update image tag to $_SHORT_SHA" && git push origin HEAD:$_BRANCH_NAME)"
      git diff --quiet && git diff --staged --quiet || (git add helm/values.yaml && git commit -m "Update image tag to $_SHORT_SHA" && git push origin HEAD:$_BRANCH_NAME)

  env:
  - 'SHORT_SHA=$_SHORT_SHA'
  - 'BRANCH_NAME=$_BRANCH_NAME'


images:
- '$_FULL_BUILD_NAME:$_TAG_PREFIX$SHORT_SHA'

substitutions:
  _FULL_BUILD_NAME: 'europe-west4-docker.pkg.dev/kiro-ops-staging/kiro-ops-staging-docker-repository/demo'
  _GIT_REPOSITORY: 'https://github.com/chrislinmpika/demo.git'
