steps:
# Step 1: Build the Docker image
- id: 'build-container'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '$_FULL_BUILD_NAME:$_TAG_PREFIX$SHORT_SHA'
  - '.'
  waitFor: ['-']

# Step 2: Update the image tag in helm/values.yaml
# This step now directly works on the checked-out code, no need to clone again
- id: 'update-image-tag'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      sed -i 's|tag:.*|tag: "'$_SHORT_SHA'"|' helm/values.yaml 
      git diff --quiet && git diff --staged --quiet || (git add helm/values.yaml && git commit -m "Update image tag to $_SHORT_SHA" && git push origin HEAD:$_BRANCH_NAME)
  env:
  - 'SHORT_SHA=$_SHORT_SHA'
  - 'BRANCH_NAME=$_BRANCH_NAME'
  waitFor:
  - 'build-container'

images:
- '$_FULL_BUILD_NAME:$_TAG_PREFIX$SHORT_SHA'

substitutions:
  _FULL_BUILD_NAME: 'europe-west4-docker.pkg.dev/kiro-ops-staging/kiro-ops-staging-docker-repository/demo'
  _GIT_REPOSITORY: 'https://github.com/chrislinmpika/demo.git'
