apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-pubsub-consumer-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.project_id: kiro-ops-staging
            resource.labels.subscription_id: kiro_ops_staging_drop_files_test
      target:
        type: Value
        value: "1"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
