helm:
  parameters:
  - name: image.tag
    value: master-4ce06a7
    forcestring: true
  - name: image.name
    value: europe-west4-docker.pkg.dev/kiro-ops-staging/kiro-ops-staging-docker-repository/demo
    forcestring: true
